clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: "varlogs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "varlogs"
          __path__: /var/log/*.log # Match all .log files
